config/routes.rb
Marysplace::Application.routes.draw do

  resources :organizations

  resources :client_notes

  namespace :api, defaults: { format: :json } do
    namespace :v0 do
      resources :checkins, only: [ :create ]
      resources :catalog_items, only: [ :index ]
    end
  end

  resources :catalog_items

  get "store/index",
    as: 'store'
  get "store/cannot_shop"
  put "store/start"
  put "store/finish/:id" => 'store#finish',
    as: 'store/finish'
  get "store/open"
  put "store/add/:id" => 'store#add',
    as: 'store/add'
  delete "store/remove/:id" => 'store#remove',
    as: 'store/remove'
  put "store/change"
  get "store/show/:id" => 'store#show',
    as: 'store/show'

  resources :locations

  resources :messages

  resources :roles, only: [ :show ]

  resources :client_flags do
    member do
      get 'resolve'
      post 'resolve_store'
    end

    collection do
      get 'resolved'
      get 'unresolved'
    end
  end

  resources :checkins do
    collection do
      get 'selfcheck'
      put 'selfcheck_post'
      get 'today'
      get 'report/:year/:month/:day' => 'checkins#daily_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'checkins#monthly_report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'checkins#annual_report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
    end
  end

  resources :points_entries
  resources :signup_lists do
    collection do
      get 'new_for'
    end
  end

  resources :points_entry_types do
    collection do
      get 'search'
      get 'all'
    end

    member do
      get 'signup_lists'
      get 'signup_list'

      get 'entry'
      get 'report/:year/:month/:day' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
          day: %r/\d\d?/
        },
        as: 'daily_report'
      get 'report/:year/:month' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
          month: %r/\d\d?/,
        },
        as: 'monthly_report'
      get 'report/:year' => 'points_entry_types#report',
        constraints: {
          year: %r/\d{4}/,
        },
        as: 'annual_report'
      get 'report'
    end
  end

  resources :clients do
    collection do
      get 'all'
      get 'search'
    end

    member do
      get 'barcode'
      get 'card'
      post 'checkin_code'
      get 'checkins'
      get 'entries'
      get 'entry'
      get 'flags'
      get 'new_login'
      get 'notes'
      put 'create_login'
      get 'purchases'
    end
  end

  get "welcome/index"
  resources :users, except: [ :destroy ] do
    member do
      get  'entries'
      post 'preference'
    end
  end

  resources :password_resets,
    except: [ :destroy ]

  resource :user_session, only: [ :new, :create, :destroy ]

  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  root :to => 'welcome#index'

end

app/models/catalog_item.rb
class CatalogItem < ActiveRecord::Base
  attr_accessible :cost, :description, :is_available, :name, :added_by_id
  validates :cost,
    presence: true,
    numericality: {
      only_integer: true
    }
  validates :name,
    presence: true,
    uniqueness: true

  belongs_to :added_by,
    class_name: "User"
end

app/controllers/api/v0/catalog_items_controller.rb
module API
  module V0
    class CatalogItemsController < ApplicationController
      before_filter :require_user

      # GET /api/v0/catalog_items.json
      def index
        @items = CatalogItem.all

        render json: @items
      end
    end
  end
end

app/controllers/catalog_items_controller.rb
class CatalogItemsController < ApplicationController
  before_filter :require_user
  authorize_resource

  # GET /catalog_items
  # GET /catalog_items.json
  def index
    @catalog_items = CatalogItem.all
  end

  # GET /catalog_items/1
  def show
    @catalog_item = CatalogItem.find(params[:id])
  end

  # GET /catalog_items/new
  def new
    @catalog_item = CatalogItem.new
  end

  # GET /catalog_items/1/edit
  def edit
    @catalog_item = CatalogItem.find(params[:id])
  end

  # POST /catalog_items
  # POST /catalog_items.json
  def create
    @catalog_item = CatalogItem.new(params[:catalog_item])
    @catalog_item.added_by = current_user

    if @catalog_item.save
      redirect_to @catalog_item,
        notice: 'Catalog item was successfully created.'
    else
      render :new
    end
  end

  # PUT /catalog_items/1
  # PUT /catalog_items/1.json
  def update
    @catalog_item = CatalogItem.find(params[:id])

    respond_to do |format|
      if @catalog_item.update_attributes(params[:catalog_item])
        format.html {
          redirect_to @catalog_item,
            notice: 'Catalog item was successfully updated.'
        }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json {
          render json: @catalog_item.errors,
            status: :unprocessable_entity
        }
      end
    end
  end

  # DELETE /catalog_items/1
  # DELETE /catalog_items/1.json
  def destroy
    @catalog_item = CatalogItem.find(params[:id])
    @catalog_item.destroy

    respond_to do |format|
      format.html { redirect_to catalog_items_url }
      format.json { head :no_content }
    end
  end
end

app/views/catalog_items/_catalog_item.html.haml
%tr
  %td= link_to catalog_item.name, catalog_item
  %td= catalog_item.cost
  %td= catalog_item.description
  %td
    - if catalog_item.is_available
      Yes
    - else
      No

app/views/catalog_items/_context_navigation.html.haml
%ul.nav.nav-tabs
  %li= link_to "Store", store_path
  %li= link_to "Catalog", catalog_items_path
  - if can? :create, CatalogItem
    %li= link_to 'New Item', new_catalog_item_path
  - if defined? catalog_item
    - if catalog_item.id
      - if can? :update, CatalogItem
        %li= link_to 'Change', edit_catalog_item_path(catalog_item)
      - if can? :destroy, CatalogItem
        %li= link_to 'Destroy', catalog_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/catalog_items/_form.html.haml
= form_for catalog_item, role: 'form' do |f|
  - if catalog_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(catalog_item.errors.count, "error")} prohibited this catalog_item from being saved:"
      %ul
        - catalog_item.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :cost
    = f.number_field :cost, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .checkbox
    = f.label :is_available do
      = f.check_box :is_available
      Is Available
  .form-group
    = f.submit 'Save', class: 'btn btn-primary btn-block'
    = cancel_button

app/views/catalog_items/edit.html.haml
= content_for(:title) do
  Changing Catalog: #{@catalog_item.name}

= content_for(:context_navigation) do
  = render 'context_navigation'

= render 'form'

app/views/catalog_items/index.html.haml
= content_for(:title) do
  Store Catalog

= content_for(:context_navigation) do
  = render 'context_navigation'

%table.table
  %tr
    %th Name
    %th Cost
    %th Description
    %th Is available
  = render @catalog_items

app/views/catalog_items/new.html.haml
= content_for(:title) do
  New Catalog Item

= content_for(:context_navigation) do
  = render 'context_navigation'

= render 'form', catalog_item: @catalog_item

app/views/catalog_items/show.html.haml
= content_for(:title) do
  Catalog: #{@catalog_item.name}


= content_for(:context_navigation) do
  = render 'context_navigation', catalog_item: @catalog_item

%dl
  %dt Name
  %dd= @catalog_item.name
  %dt Cost
  %dd= @catalog_item.cost
  %dt Description
  %dd= @catalog_item.description
  %dt Is Available?
  %dd= @catalog_item.is_available